# Generated by Django 5.0.6 on 2024-06-07 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker_App', '0002_alter_userbalancemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='income',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
